# Generated by Django 4.0.5 on 2022-06-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFT_Data',
            new_name='NFTData',
        ),
    ]
